class AmazonPrime
{
	public static void main(String[] prime)
	{
		String kannadamovies[]={"Love Mocktail","Dia","Kantara","Birbal","Kavaludaari","Rathnan Prapancha","Ikkat","One cut Two cut","French Biriyani","Yuvarathnaa","Kotigobba 3","Act 1978","Gantumoote","Ulidavaru Kandanthe","Jai Bhima","Sapta Sagaradaache Ello – Side A","Sapta Sagaradaache Ello – Side B","Meja Suri","Meka Suri 2","Firefly","Sees Kaddi","Blink","Shakahari","Humble Politician Nograj","Happy New Year","Raajakumara","Katha Sangama","Tagaru","Pailwaan","Man of the Match"};
		String hindimovies[]={"Be Happy","Tiku weds Sheru","Jalsa","Sardar Udham","Mirzapur","Badla","Drishyam","Shershaah 2","Sooryavanshi","Bell Bottom","Rakta Charitra","Company","Shootout at Lokhandwala","Vaastav: The Reality","O’Romeo","Runway 34","Thank God","Jug Jug Jeeyo","Govinda Naam Mera","Rocky Aur Rani Ki Prem Kahani","Aye Watan…Mere Watan","Ram Setu","Majaa Maa","Neeyat","Phone Bhoot","Fukrey 3","Jee Le Zara","War","Gold","Udaan"};
		String tamilmovies[]={"Saani Kaayidham","Jai Bhim","Maargan","Kombuseevi","96","Pariyerum Perumal","Asuran","Anbe Sivam","Uriyadi","Peranbu","Iruvar ","Nayakan","Adhe Kangal","Aruuvi","Kaala","Theeran Adhigaaram Ondru","Thanal","Soorarai Pottru","Peri","Rangoli","Pudhupettai","NotA","Tamil Padam 2","Adutha Veedu","Magamuni","Sathuranga Vettai ","Madras","Maya","Nenjam Marappathillai","Kaakha Kaakha"};
		String telgumovies[]={"Aravinda Sametha Veera Raghava","Bhai","DJ","Manmadhudu 2","Bheemla Nayak","Red","Agent Sai Srinivasa Athreya","Sarileru Neekevvaru","Ala Vaikunthapuramulo","Gopala Gopala","F2: Fun and Frustration","F3: Fun and Frustration","Nenu Local","Kalki","Jaanu","Chitralahari","Thank You","Anando Brahma","Varisu","Hunt","Ekkadiki Pothavu Chinnavada","Sarangapani Jathakam","Karthikeya","Tarun Bhascker’s films","Paagal","Pushpa: The Rule","Maharshi","Saaho","Gatham","Nishabdham"};
		String malyalammovies[]={"No Man’s Land","Sufiyum Sujatayum","Bhramam","Fourth RIver","Sara’s","C U Soon","Saajan Bakery Since 1962","Drishyam 2","Abhilasham","The Priest","Anchakkallakokkan: Porattu","Premalu","Lucifer","Joji","Kumbalangi Nights","Ayyappanum Koshiyum","Helen","Android Kunjappan Ver 5.25","Unda","Jallikattu","Home","Kuruthi","Aavesham","Pada","Malayankunju","Jo and Jo","Jibooty","Naradhan","Veyil","Pallotty"};
		String englishmovies[]={"Terminator 2: Judgment Day","The Matrix","Ready Player One","The Wrecking Crew","La La Land","RoboCop","The Prestige","One Night in Miami","Blow the Man Down","Barbershop","The Big Lebowski","The Other Guys","The Idea of You","Sinners","Weapon","Black Bag","To Live and Die in L.A.","The First Omen","No Time to Die","Casino Royale","Spider-Man: No Way Home","Ready Player One","Blow the Man Down","Kung Fu Panda 4","Madagascar 3: Europe’s Most Wanted","Sherk 2","The Boss Baby","Fight Club","Forrest Gump","The Usual Suspects"};
		System.out.println("Amazon Prime movies are:");
		System.out.println("Kannada Movies are:");
		String k1="Love Mocktail";
		String k2="Dia";
		String k3="Kantara";
		String k4="Birbal";
		String k5="Kavaludaari";
		String k6="Rathnan Prapancha";
		String k7="Ikkat";
		String k8="One cut Two cut";
		String k9="French Biriyani";
		String k10="Yuvarathnaa";
		String k11="Kotigobba 3";
		String k12="Act 1978";
		String k13="Gantumoote";
		String k14="Ulidavaru Kandanthe";
		String k15="Jai Bhima";
		String k16="Sapta Sagaradaache Ello – Side A";
		String k17="Sapta Sagaradaache Ello – Side B";
		String k18="Meja Suri";
		String k19="Meka Suri 2";
		String k20="Firefly";
		String k21="Blink";
		String k22="Shakahari";
		String k23="Humble Politician Nograj";
		String k24="Happy New Year";
		String k25="Raajakumara";
		String k26="Katha Sangama";
		String k27="Tagaru";
		String k28="Pailwaan";
		String k29="Man of the Match";
		String k30="Sees Kaddi";
		String properties[]={k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,k11,k12,k13,k14,k15,k16,k17,k18,k19,k20,k21,k22,k23,k24,k25,k26,k27,k28,k29,k30};
		for(String property:properties)
			System.out.println(property);
		System.out.println("Hindi Movies are:");
		String h1="Be Happy";
		String h2="Tiku weds Sheru";
		String h3="Jalsa";
		String h4="Sardar Udham";
		String h5="Mirzapur";
		String h6="Badla";
		String h7="Drishyam";
		String h8="Shershaah 2";
		String h9="Sooryavanshi";
		String h10="Bell Bottom";
		String h11="Rakta Charitra";
		String h12="Company";
		String h13="Shootout at Lokhandwala";
		String h14="Vaastav: The Reality";
		String h15="O’Romeo";
		String h16="Runway 34";
		String h17="Thank God";
		String h18="Jug Jug Jeeyo";
		String h19="Govinda Naam Mera";
		String h20="Rocky Aur Rani Ki Prem Kahani";
		String h21="Aye Watan…Mere Watan";
		String h22="Ram Setu";
		String h23="Majaa Maa";
		String h24="Neeyat";
		String h25="Phone Bhoot";
		String h26="Fukrey 3";
		String h27="Jee Le Zara";
		String h28="War";
		String h29="Gold";
		String h30="Udaan";
		String methods[]={h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13,h14,h15,h16,h17,h18,h19,h20,h21,h22,h23,h24,h25,h26,h27,h28,h29,h30};
		for(String method:methods)
			System.out.println(method);
		System.out.println("Tamil Movies are:");
		String t1="Saani Kaayidham";
		String t2="Jai Bhim";
		String t3="Maargan";
		String t4="Kombuseevi";
		String t5="96";
		String t6="Pariyerum Perumal";
		String t7="Asuran";
		String t8="Anbe Sivam";
		String t9="Uriyadi";
		String t10="Peranbu";
		String t11="Iruvar ";
		String t12="Nayakan";
		String t13="Adhe Kangal";
		String t14="Aruuvi";
		String t15="Kaala";
		String t16="Theeran Adhigaaram Ondru";
		String t17="Thanal";
		String t18="Soorarai Pottru";
		String t19="Peri";
		String t20="Rangoli";
		String t21="Pudhupettai";
		String t22="NotA";
		String t23="Tamil Padam 2";
		String t24="Adutha Veedu";
		String t25="Magamuni";
		String t26="Sathuranga Vettai ";
		String t27="Madras";
		String t28="Maya";
		String t29="Nenjam Marappathillai";
		String t30="Kaakha Kaakha";
		String caps[]={t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t18,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30};
		for(String cap:caps)
			System.out.println(cap);
		System.out.println("Telghu Movies are:");
		String te1="Aravinda Sametha Veera Raghava";
		String te2="Bhai";
		String te3="DJ";
		String te4="Manmadhudu 2";
		String te5="Red";
		String te6="Agent Sai Srinivasa Athreya";
		String te7="Sarileru Neekevvaru";
		String te8="Ala Vaikunthapuramulo";
		String te9="Gopala Gopala";
		String te10="F2: Fun and Frustration";
		String te11="F3: Fun and Frustration";
		String te12="Nenu Local";
		String te13="Kalki";
		String te14="Jaanu";
		String te15="Chitralahari";
		String te16="Thank You";
		String te17="Anando Brahma";
		String te18="Varisu";
		String te19="Hunt";
		String te20="Ekkadiki Pothavu Chinnavada";
		String te21="Sarangapani Jathakam";
		String te22="Karthikeya";
		String te23="Tarun Bhascker’s films";
		String te24="Paagal";
		String te25="Pushpa: The Rule";
		String te26="Maharshi";
		String te29="Gatham";
		String te30="Nishabdham";
		String dolls[]={te1,te2,te3,te4,te5,te6,te7,te8,te9,te10,te11,te12,t13,te14,te15,te16,te17,te18,te19,te20,te21,te22,te23,te24,te25,te26,te29,te30};
		for(String doll:dolls)
			System.out.println(doll);
		System.out.println("Malyalam  Movies are:");
		String m1="No Man’s Land";
		String m2="Sufiyum Sujatayum";
		String m3="Bhramam";
		String m4="Fourth RIver";
		String m5="Sara’s";
		String m6="C U Soon";
		String m7="Saajan Bakery Since 1962";
		String m8="Drishyam 2";
		String m9="Abhilasham";
		String m10="The Priest";
		String m11="Anchakkallakokkan: Porattu";
		String m12="Premalu";
		String m13="Lucifer";
		String m14="Joji";
		String m15="Kumbalangi Nights";
		String m16="Ayyappanum Koshiyum";
		String m17="Helen";
		String m18="Android Kunjappan Ver 5.25";
		String m19="Unda";
		String m20="Jallikattu";
		String m21="Home";
		String m22="Kuruthi";
		String m23="Aavesham";
		String m24="Pada";
		String m25="Malayankunju";
		String m26="Jo and Jo";
		String m27="Pallotty";
		String m28="Jibooty";
		String m29="Naradhan";
		String m30="Veyil";
		String talls[]={m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25,m26,m27,m28,m29,m30};
		for(String tall:talls)
			System.out.println(tall);
		System.out.println("English Movies are:");
		String e1="Terminator 2: Judgment Day";
		String e2="The Matrix";
		String e3="Ready Player One";
		String e4="The Wrecking Crew";
		String e5="La La Land";
		String e6="RoboCop";
		String e7="The Prestige";
		String e8="One Night in Miami";
		String e9="Blow the Man Down";
		String e10="Barbershop";
		String e11="The Big Lebowski";
		String e12="The Other Guys";
		String e13="The Idea of You";
		String e14="Sinners";
		String e15="Weapon";
		String e16="Black Bag";
		String e17="To Live and Die in L.A.";
		String e18="The First Omen";
		String e19="No Time to Die";
		String e20="Casino Royale";
		String e21="Spider-Man: No Way Home";
		String e22="Ready Player One";
		String e23="Blow the Man Down";
		String e24="Kung Fu Panda 4";
		String e25="Madagascar 3: Europe’s Most Wanted";
		String e26="Sherk 2";
		String e27="The Boss Baby";
		String e28="Fight Club";
		String e29="Forrest Gump";
		String e30="The Usual Suspects";
		String halls[]={e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14,e15,e16,e17,e18,e19,e20,e21,e22,e23,e23,e25,e26,e27,e28,e29,e30};
		for(String hall:halls)
			System.out.println(hall);		
	}
}	
		