class Netflix
{
	public static void main(String[] prime)
	{
		String kannadamovies[]={"Baghera","U-Turn","Govinda Govinda","Ayana","Mundina Nildana","Ondu Motteya Kathe","Thithi","Nathicharami","Minchu Murali","Annaatthe","","","","","","","","","","","","","","","","","","","",""};
		String hindimovies[]={"Dhoom Dhaam","Vijay 69","Sector 36","Chor Nikal Ke Bhaga","haq","De De Pyaar De 2","Tere Ishk Mein","Mardaani ","Mardaani 2","Jolly LLB 3","Jogi","Barfi","Haseen Dillruba","Chopsticks","Raja Hindustani","Mohabbatein","Ajab Prem Ki Ghazab Kahani","Hum Dil De Chuke Sanam","Love Aaj Kal","Dhurandhar","Mission Majnu","Kohrra","Single Salma","Raat Akeli Hai – The Bansal Murders","Sunny Sanskari Ki Tulsi Kumari","Dhoom3","Tiger Zinda Hai","war","Bade Miyan Chote Miyan","Yeh Jawaani Hai Deewani"};
		String tamilmovies[]={"Maharaja","Leo","Don","Doctor","Thunivu","Amaran","Love Today","Mandela","Kannum Kannum Kollaiyadithaal","Super Deluxe","Magamuni","Andhaghaaram","Oho Enthan Baby","Paava Kadhaigal","Revolver Rita","Good Bad Ugly","Thug life","Retro","VidaaMuyarchi","Kaantha","Bison","Dragon","Perusu","Untitled Pradeep Ranganathan Film","Kara","Suriya 46","Jigarthanda DoubleX","Visaranai","Sorgavasal","G.O.A.T"};
		String telgumovies[]={"Major","Pitta Kathalu","Bhaje Vaayu Vegam","Gangs of Godavari","Anukokunda Oka Roju","Oh! Baby","Paragu","Seethamma Vakitlo Sirimalle Chettu","Bro","Sindhooram","Daaku","Virata Parvam","Dasara","Uma Maheswara Ugra Roopasya","Lucky Bhaska","Court: State vs A Nobody","Bhola Shankar","God Father","Khushi","Waltair Veerayya","Puspha","Saripodhaa Sanivaaram","Hit 3","Devara","Hi Nanna","RRR ","Salaar: Part 1 – Ceasefire","Guntur Kaaram","Cinema Bandi","Krishna and His Leela"};
		String malyalammovies[]={"Minnal Murali","Irul","Kappela","Maniyarayile Ashokan","Jana Gana Mana","Nanpakal Nerathu Mayakkam","Thallumaala","Uyare","Nayattu","Virus","Thondimuthalum Driksakshiyum","Joji","Angamaly Diaries","Iratta","Rekha","Kumari","Ayalvaashi","Aarkkariyam","Aanum Pennum","Anjaam Pathiraa","Aravindante Athidhikal","Dear Friend","Ee.Ma.Yau","Forensic","Ezra","Halal Love Story","Luca","Hridayam","Maheshinte Prathikaaram","Meppadiyan"};
		String englishmovies[]={"The Gray Man","Extraction","Red Notice","Army of the Dead","The Old Guard","Triple Frontier","6 Underground","Black Adam","The Night Comes for Us","Kate","Spider-Man: Into the Spider-Verse","Bright","project Power","The Adam Project","Enola Holmes 1 & 2","Gerald’s Game","Bird Box","Hush","The Platform","Cam","Fractured","I Am Mother","The Devil All the Time","Oxygen","Hypnotic","Roma","Murder Mystery 1 & 2","The Love Birds","Yes Day","Dolemite Is My Name"};
		System.out.println("Amazon Prime movies are:");
		System.out.println("Kannada Movies are:");
		System.out.println(kannadamovies[0]+"\n"+kannadamovies[1]+"\n"+kannadamovies[2]+"\n"+kannadamovies[3]+"\n"+kannadamovies[4]+"\n"+kannadamovies[5]+"\n"+kannadamovies[6]+"\n"+kannadamovies[7]+"\n"+kannadamovies[8]+"\n"+kannadamovies[9]+"\n"+kannadamovies[10]+"\n"+kannadamovies[11]+"\n"+kannadamovies[12]+"\n"+kannadamovies[13]+"\n"+kannadamovies[14]+"\n"+kannadamovies[15]+"\n"+kannadamovies[16]+"\n"+kannadamovies[17]+"\n"+kannadamovies[18]+"\n"+kannadamovies[19]+"\n"+kannadamovies[20]+"\n"+kannadamovies[21]+"\n"+kannadamovies[22]+"\n"+kannadamovies[23]+"\n"+kannadamovies[24]+"\n"+kannadamovies[25]+"\n"+kannadamovies[26]+"\n"+kannadamovies[27]+"\n"+kannadamovies[28]+"\n"+kannadamovies[29]);
		System.out.println("Hindi Movies are:");
		System.out.println(hindimovies[0]+"\n"+hindimovies[1]+"\n"+hindimovies[2]+"\n"+hindimovies[3]+"\n"+hindimovies[4]+"\n"+hindimovies[5]+"\n"+hindimovies[6]+"\n"+hindimovies[7]+"\n"+hindimovies[8]+"\n"+hindimovies[9]+"\n"+hindimovies[10]+"\n"+hindimovies[11]+"\n"+hindimovies[12]+"\n"+hindimovies[13]+"\n"+hindimovies[14]+"\n"+hindimovies[15]+"\n"+hindimovies[16]+"\n"+hindimovies[17]+"\n"+hindimovies[18]+"\n"+hindimovies[19]+"\n"+hindimovies[20]+"\n"+hindimovies[21]+"\n"+hindimovies[22]+"\n"+hindimovies[23]+"\n"+hindimovies[24]+"\n"+hindimovies[25]+"\n"+hindimovies[26]+"\n"+hindimovies[27]+"\n"+hindimovies[28]+"\n"+hindimovies[29]);
		System.out.println("Tamil Movies are:");
		System.out.println(tamilmovies[0]+"\n"+tamilmovies[1]+"\n"+tamilmovies[2]+"\n"+tamilmovies[3]+"\n"+tamilmovies[4]+"\n"+tamilmovies[5]+"\n"+tamilmovies[6]+"\n"+tamilmovies[7]+"\n"+tamilmovies[8]+"\n"+tamilmovies[9]+"\n"+tamilmovies[10]+"\n"+tamilmovies[11]+"\n"+tamilmovies[12]+"\n"+tamilmovies[13]+"\n"+tamilmovies[14]+"\n"+tamilmovies[15]+"\n"+tamilmovies[16]+"\n"+tamilmovies[17]+"\n"+tamilmovies[18]+"\n"+tamilmovies[19]+"\n"+tamilmovies[20]+"\n"+tamilmovies[21]+"\n"+tamilmovies[22]+"\n"+tamilmovies[23]+"\n"+tamilmovies[24]+"\n"+tamilmovies[25]+"\n"+tamilmovies[26]+"\n"+tamilmovies[27]+"\n"+tamilmovies[28]+"\n"+tamilmovies[29]);
		System.out.println("Telghu Movies are:");
		System.out.println(telgumovies[0]+"\n"+telgumovies[1]+"\n"+telgumovies[2]+"\n"+telgumovies[3]+"\n"+telgumovies[4]+"\n"+telgumovies[5]+"\n"+telgumovies[6]+"\n"+telgumovies[7]+"\n"+telgumovies[8]+"\n"+telgumovies[9]+"\n"+telgumovies[10]+"\n"+telgumovies[11]+"\n"+telgumovies[12]+"\n"+telgumovies[13]+"\n"+telgumovies[14]+"\n"+telgumovies[15]+"\n"+telgumovies[16]+"\n"+telgumovies[17]+"\n"+telgumovies[18]+"\n"+telgumovies[19]+"\n"+telgumovies[20]+"\n"+telgumovies[21]+"\n"+telgumovies[22]+"\n"+telgumovies[23]+"\n"+telgumovies[24]+"\n"+telgumovies[25]+"\n"+telgumovies[26]+"\n"+telgumovies[27]+"\n"+telgumovies[28]+"\n"+telgumovies[29]);
		System.out.println("Malyalam  Movies are:");
		System.out.println(malyalammovies[0]+"\n"+malyalammovies[1]+"\n"+malyalammovies[2]+"\n"+malyalammovies[3]+"\n"+malyalammovies[4]+"\n"+malyalammovies[5]+"\n"+malyalammovies[6]+"\n"+malyalammovies[7]+"\n"+malyalammovies[8]+"\n"+malyalammovies[9]+"\n"+malyalammovies[10]+"\n"+malyalammovies[11]+"\n"+malyalammovies[12]+"\n"+malyalammovies[13]+"\n"+malyalammovies[14]+"\n"+malyalammovies[15]+"\n"+malyalammovies[16]+"\n"+malyalammovies[17]+"\n"+malyalammovies[18]+"\n"+malyalammovies[19]+"\n"+malyalammovies[20]+"\n"+malyalammovies[21]+"\n"+malyalammovies[22]+"\n"+malyalammovies[23]+"\n"+malyalammovies[24]+"\n"+malyalammovies[25]+"\n"+malyalammovies[26]+"\n"+malyalammovies[27]+"\n"+malyalammovies[28]+"\n"+malyalammovies[29]);
		System.out.println("English Movies are:");
		System.out.println(englishmovies[0]+"\n"+englishmovies[1]+"\n"+englishmovies[2]+"\n"+englishmovies[3]+"\n"+englishmovies[4]+"\n"+englishmovies[5]+"\n"+englishmovies[6]+"\n"+englishmovies[7]+"\n"+englishmovies[8]+"\n"+englishmovies[9]+"\n"+englishmovies[10]+"\n"+englishmovies[11]+"\n"+englishmovies[12]+"\n"+englishmovies[13]+"\n"+englishmovies[14]+"\n"+englishmovies[15]+"\n"+englishmovies[16]+"\n"+englishmovies[17]+"\n"+englishmovies[18]+"\n"+englishmovies[19]+"\n"+englishmovies[20]+"\n"+englishmovies[21]+"\n"+englishmovies[22]+"\n"+englishmovies[23]+"\n"+englishmovies[24]+"\n"+englishmovies[25]+"\n"+englishmovies[26]+"\n"+englishmovies[27]+"\n"+englishmovies[28]+"\n"+englishmovies[29]);
	}
}	
		