class ZeptoExecutor
{
	public static void main(String[] ze)
	{
		String itemName="Kurkure";
		double price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Sandwich";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Burger";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="French fries";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Coca Cola";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Apples";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Bananas";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Oranges";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Mangoes";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Tomatoes";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Potatoes";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Onions";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Carrots";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Spinach";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Capsicum";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Milk";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Curd";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Butter";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Cheese";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Paneer";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Eggs";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Bread";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Cornflakes";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Rice";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Atta";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Toor Dal";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Moong Dal";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Sugar";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Salt";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Cooking oil";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Dark fantasy";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Dairy Milk";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Chips";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Namkeen";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Instant noodles";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Pasta";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Oats";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Tea";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Coffee";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Soft drinks";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Fruit Juice";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Energy Drink";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Soap";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Shampoo";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Conditioner";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Toothpaste";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Toothbrush";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Face Wash";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Detergent powder";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Dishwash liquid";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Floor Cleaner";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Garbage bags";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Tissue paper";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Frozen peas";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Frozen paratha";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Ready meals";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Pet food";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Baby diapers";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Sanitary pads";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
		itemName="Ice cream";
		price=Zepto.search(itemName);
		System.out.println("The price of " + itemName + " is " + price);
	
		
	}
}