class ZeptoRunner
{
	public static void main(String[] Zr)
	{
		String itemName="Sandwich";
		int quantity=3;
		double pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Sandwich";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Sandwich";
		quantity=4;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Sandwich";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Sandwich";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Apples";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Oranges";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Bananas";
		quantity=4;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Mangoes";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Tomatoes";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Potatoes";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Onions";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Carrots";
		quantity=5;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Spinach";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Capsicum";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Milk";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Curd";
		quantity=5;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Butter";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Cheese";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Eggs";
		quantity=8;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Bread";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Cornflakes";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Rice";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Atta";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Toor Dal";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Moong Dal";
		quantity=4;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Sugar";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Salt";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Cooking oil";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Dark fantasy";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Dairy Milk";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Chips";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Namkeen";
		quantity=4;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Instant noodles";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Pasta";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Oats";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Tea";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Coffee";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Soft drinks";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Fruit Juice";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Energy Drink";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Soap";
		quantity=6;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Shampoo";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Conditioner";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Toothpaste";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Toothbrush";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Face Wash";
		quantity=5;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Detergent powder";
		quantity=7;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Dishwash liquid";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Floor cleaner";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Garbage bags";
		quantity=9;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Tissue papaer";
		quantity=12;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Frozen peas";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Frozen  paratha";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Ready meals";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Pet food";
		quantity=5;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Baby diapers";
		quantity=3;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Sanitary pads";
		quantity=2;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
		itemName="Ice cream";
		quantity=10;
		pricewithquantity=Zepto.search(itemName,quantity);
		System.out.println("The price of " + itemName + "is" + pricewithquantity);
	
	}
}