class AmazonPrime
{
	public static void main(String[] prime)
	{
		String kannadamovies[]={"Love Mocktail","Dia","Kantara","Birbal","Kavaludaari","Rathnan Prapancha","Ikkat","One cut Two cut","French Biriyani","Yuvarathnaa","Kotigobba 3","Act 1978","Gantumoote","Ulidavaru Kandanthe","Jai Bhima","Sapta Sagaradaache Ello – Side A","Sapta Sagaradaache Ello – Side B","Meja Suri","Meka Suri 2","Firefly","Sees Kaddi","Blink","Shakahari","Humble Politician Nograj","Happy New Year","Raajakumara","Katha Sangama","Tagaru","Pailwaan","Man of the Match"};
		String hindimovies[]={"Be Happy","Tiku weds Sheru","Jalsa","Sardar Udham","Mirzapur","Badla","Drishyam","Shershaah 2","Sooryavanshi","Bell Bottom","Rakta Charitra","Company","Shootout at Lokhandwala","Vaastav: The Reality","O’Romeo","Runway 34","Thank God","Jug Jug Jeeyo","Govinda Naam Mera","Rocky Aur Rani Ki Prem Kahani","Aye Watan…Mere Watan","Ram Setu","Majaa Maa","Neeyat","Phone Bhoot","Fukrey 3","Jee Le Zara","War","Gold","Udaan"};
		String tamilmovies[]={"Saani Kaayidham","Jai Bhim","Maargan","Kombuseevi","96","Pariyerum Perumal","Asuran","Anbe Sivam","Uriyadi","Peranbu","Iruvar ","Nayakan","Adhe Kangal","Aruuvi","Kaala","Theeran Adhigaaram Ondru","Thanal","Soorarai Pottru","Peri","Rangoli","Pudhupettai","NotA","Tamil Padam 2","Adutha Veedu","Magamuni","Sathuranga Vettai ","Madras","Maya","Nenjam Marappathillai","Kaakha Kaakha"};
		String telgumovies[]={"Aravinda Sametha Veera Raghava","Bhai","DJ","Manmadhudu 2","Bheemla Nayak","Red","Agent Sai Srinivasa Athreya","Sarileru Neekevvaru","Ala Vaikunthapuramulo","Gopala Gopala","F2: Fun and Frustration","F3: Fun and Frustration","Nenu Local","Kalki","Jaanu","Chitralahari","Thank You","Anando Brahma","Varisu","Hunt","Ekkadiki Pothavu Chinnavada","Sarangapani Jathakam","Karthikeya","Tarun Bhascker’s films","Paagal","Pushpa: The Rule","Maharshi","Saaho","Gatham","Nishabdham"};
		String malyalammovies[]={"No Man’s Land","Sufiyum Sujatayum","Bhramam","Fourth RIver","Sara’s","C U Soon","Saajan Bakery Since 1962","Drishyam 2","Abhilasham","The Priest","Anchakkallakokkan: Porattu","Premalu","Lucifer","Joji","Kumbalangi Nights","Ayyappanum Koshiyum","Helen","Android Kunjappan Ver 5.25","Unda","Jallikattu","Home","Kuruthi","Aavesham","Pada","Malayankunju","Jo and Jo","Jibooty","Naradhan","Veyil","Pallotty"};
		String englishmovies[]={"Terminator 2: Judgment Day","The Matrix","Ready Player One","The Wrecking Crew","La La Land","RoboCop","The Prestige","One Night in Miami","Blow the Man Down","Barbershop","The Big Lebowski","The Other Guys","The Idea of You","Sinners","Weapon","Black Bag","To Live and Die in L.A.","The First Omen","No Time to Die","Casino Royale","Spider-Man: No Way Home","Ready Player One","Blow the Man Down","Kung Fu Panda 4","Madagascar 3: Europe’s Most Wanted","Sherk 2","The Boss Baby","Fight Club","Forrest Gump","The Usual Suspects"};
		System.out.println("Amazon Prime movies are:");
		
		/*System.out.println(kannadamovies[0]+"\n"+kannadamovies[1]+"\n"+kannadamovies[2]+"\n"+kannadamovies[3]+"\n"+kannadamovies[4]+"\n"+kannadamovies[5]+"\n"+kannadamovies[6]+"\n"+kannadamovies[7]+"\n"+kannadamovies[8]+"\n"+kannadamovies[9]+"\n"+kannadamovies[10]+"\n"+kannadamovies[11]+"\n"+kannadamovies[12]+"\n"+kannadamovies[13]+"\n"+kannadamovies[14]+"\n"+kannadamovies[15]+"\n"+kannadamovies[16]+"\n"+kannadamovies[17]+"\n"+kannadamovies[18]+"\n"+kannadamovies[19]+"\n"+kannadamovies[20]+"\n"+kannadamovies[21]+"\n"+kannadamovies[22]+"\n"+kannadamovies[23]+"\n"+kannadamovies[24]+"\n"+kannadamovies[25]+"\n"+kannadamovies[26]+"\n"+kannadamovies[27]+"\n"+kannadamovies[28]+"\n"+kannadamovies[29]);*/
		
		/*System.out.println(hindimovies[0]+"\n"+hindimovies[1]+"\n"+hindimovies[2]+"\n"+hindimovies[3]+"\n"+hindimovies[4]+"\n"+hindimovies[5]+"\n"+hindimovies[6]+"\n"+hindimovies[7]+"\n"+hindimovies[8]+"\n"+hindimovies[9]+"\n"+hindimovies[10]+"\n"+hindimovies[11]+"\n"+hindimovies[12]+"\n"+hindimovies[13]+"\n"+hindimovies[14]+"\n"+hindimovies[15]+"\n"+hindimovies[16]+"\n"+hindimovies[17]+"\n"+hindimovies[18]+"\n"+hindimovies[19]+"\n"+hindimovies[20]+"\n"+hindimovies[21]+"\n"+hindimovies[22]+"\n"+hindimovies[23]+"\n"+hindimovies[24]+"\n"+hindimovies[25]+"\n"+hindimovies[26]+"\n"+hindimovies[27]+"\n"+hindimovies[28]+"\n"+hindimovies[29]);*/
		
		/*System.out.println(tamilmovies[0]+"\n"+tamilmovies[1]+"\n"+tamilmovies[2]+"\n"+tamilmovies[3]+"\n"+tamilmovies[4]+"\n"+tamilmovies[5]+"\n"+tamilmovies[6]+"\n"+tamilmovies[7]+"\n"+tamilmovies[8]+"\n"+tamilmovies[9]+"\n"+tamilmovies[10]+"\n"+tamilmovies[11]+"\n"+tamilmovies[12]+"\n"+tamilmovies[13]+"\n"+tamilmovies[14]+"\n"+tamilmovies[15]+"\n"+tamilmovies[16]+"\n"+tamilmovies[17]+"\n"+tamilmovies[18]+"\n"+tamilmovies[19]+"\n"+tamilmovies[20]+"\n"+tamilmovies[21]+"\n"+tamilmovies[22]+"\n"+tamilmovies[23]+"\n"+tamilmovies[24]+"\n"+tamilmovies[25]+"\n"+tamilmovies[26]+"\n"+tamilmovies[27]+"\n"+tamilmovies[28]+"\n"+tamilmovies[29]);*/
		
		/*System.out.println(telgumovies[0]+"\n"+telgumovies[1]+"\n"+telgumovies[2]+"\n"+telgumovies[3]+"\n"+telgumovies[4]+"\n"+telgumovies[5]+"\n"+telgumovies[6]+"\n"+telgumovies[7]+"\n"+telgumovies[8]+"\n"+telgumovies[9]+"\n"+telgumovies[10]+"\n"+telgumovies[11]+"\n"+telgumovies[12]+"\n"+telgumovies[13]+"\n"+telgumovies[14]+"\n"+telgumovies[15]+"\n"+telgumovies[16]+"\n"+telgumovies[17]+"\n"+telgumovies[18]+"\n"+telgumovies[19]+"\n"+telgumovies[20]+"\n"+telgumovies[21]+"\n"+telgumovies[22]+"\n"+telgumovies[23]+"\n"+telgumovies[24]+"\n"+telgumovies[25]+"\n"+telgumovies[26]+"\n"+telgumovies[27]+"\n"+telgumovies[28]+"\n"+telgumovies[29]);*/
		
		/*System.out.println(malyalammovies[0]+"\n"+malyalammovies[1]+"\n"+malyalammovies[2]+"\n"+malyalammovies[3]+"\n"+malyalammovies[4]+"\n"+malyalammovies[5]+"\n"+malyalammovies[6]+"\n"+malyalammovies[7]+"\n"+malyalammovies[8]+"\n"+malyalammovies[9]+"\n"+malyalammovies[10]+"\n"+malyalammovies[11]+"\n"+malyalammovies[12]+"\n"+malyalammovies[13]+"\n"+malyalammovies[14]+"\n"+malyalammovies[15]+"\n"+malyalammovies[16]+"\n"+malyalammovies[17]+"\n"+malyalammovies[18]+"\n"+malyalammovies[19]+"\n"+malyalammovies[20]+"\n"+malyalammovies[21]+"\n"+malyalammovies[22]+"\n"+malyalammovies[23]+"\n"+malyalammovies[24]+"\n"+malyalammovies[25]+"\n"+malyalammovies[26]+"\n"+malyalammovies[27]+"\n"+malyalammovies[28]+"\n"+malyalammovies[29]);*/
		
		/*System.out.println(englishmovies[0]+"\n"+englishmovies[1]+"\n"+englishmovies[2]+"\n"+englishmovies[3]+"\n"+englishmovies[4]+"\n"+englishmovies[5]+"\n"+englishmovies[6]+"\n"+englishmovies[7]+"\n"+englishmovies[8]+"\n"+englishmovies[9]+"\n"+englishmovies[10]+"\n"+englishmovies[11]+"\n"+englishmovies[12]+"\n"+englishmovies[13]+"\n"+englishmovies[14]+"\n"+englishmovies[15]+"\n"+englishmovies[16]+"\n"+englishmovies[17]+"\n"+englishmovies[18]+"\n"+englishmovies[19]+"\n"+englishmovies[20]+"\n"+englishmovies[21]+"\n"+englishmovies[22]+"\n"+englishmovies[23]+"\n"+englishmovies[24]+"\n"+englishmovies[25]+"\n"+englishmovies[26]+"\n"+englishmovies[27]+"\n"+englishmovies[28]+"\n"+englishmovies[29]);*/
		System.out.println("Kannada Movies are:");
		String k1=kannadamovies[0];
		System.out.println(k1);
		String k2=kannadamovies[1];
		System.out.println(k2);
		String k3=kannadamovies[2];
		System.out.println(k3);
		String k4=kannadamovies[3];
		System.out.println(k4);
		String k5=kannadamovies[4];
		System.out.println(k5);
		String k6=kannadamovies[5];
		System.out.println(k6);
		String k7=kannadamovies[6];
		System.out.println(k7);
		String k8=kannadamovies[7];
		System.out.println(k8);
		String k9=kannadamovies[8];
		System.out.println(k9);
		String k10=kannadamovies[9];
		System.out.println(k10);
		String k11=kannadamovies[10];
		System.out.println(k11);
		String k12=kannadamovies[11];
		System.out.println(k12);
		String k13=kannadamovies[12];
		System.out.println(k13);
		String k14=kannadamovies[13];
		System.out.println(k14);
		String k15=kannadamovies[14];
		System.out.println(k15);
		String k16=kannadamovies[15];
		System.out.println(k16);
		String k17=kannadamovies[16];
		System.out.println(k17);
		String k18=kannadamovies[17];
		System.out.println(k18);
		String k19=kannadamovies[18];
		System.out.println(k19);
		String k20=kannadamovies[19];
		System.out.println(k20);
		String k21=kannadamovies[20];
		System.out.println(k21);
		String k22=kannadamovies[21];
		System.out.println(k22);
		String k23=kannadamovies[22];
		System.out.println(k23);
		String k24=kannadamovies[23];
		System.out.println(k24);
		String k25=kannadamovies[24];
		System.out.println(k25);
		String k26=kannadamovies[25];
		System.out.println(k26);
		String k27=kannadamovies[26];
		System.out.println(k27);
		String k28=kannadamovies[27];
		System.out.println(k28);
		String k29=kannadamovies[28];
		System.out.println(k29);
		String k30=kannadamovies[29];
		System.out.println(k30);
		System.out.println("Hindi Movies are:");
		String h1=hindimovies[0];
		System.out.println(h1);
		String h2=hindimovies[1];
		System.out.println(h2);
		String h3=hindimovies[2];
		System.out.println(h3);
		String h4=hindimovies[3];
		System.out.println(h4);
		String h5=hindimovies[4];
		System.out.println(h5);
		String h6=hindimovies[5];
		System.out.println(h6);
		String h7=hindimovies[6];
		System.out.println(h7);
		String h8=hindimovies[7];
		System.out.println(h8);
		String h9=hindimovies[8];
		System.out.println(h9);
		String h10=hindimovies[9];
		System.out.println(h10);
		String h11=hindimovies[10];
		System.out.println(h11);
		String h12=hindimovies[11];
		System.out.println(h12);
		String h13=hindimovies[12];
		System.out.println(h13);
		String h14=hindimovies[13];
		System.out.println(h14);
		String h15=hindimovies[14];
		System.out.println(h15);
		String h16=hindimovies[15];
		System.out.println(h16);
		String h17=hindimovies[16];
		System.out.println(h17);
		String h18=hindimovies[017];
		System.out.println(h18);
		String h19=hindimovies[18];
		System.out.println(h19);
		String h20=hindimovies[19];
		System.out.println(h20);
		String h21=hindimovies[20];
		System.out.println(h21);
		String h22=hindimovies[21];
		System.out.println(h22);
		String h23=hindimovies[22];
		System.out.println(h23);
		String h24=hindimovies[23];
		System.out.println(h24);
		String h25=hindimovies[24];
		System.out.println(h25);
		String h26=hindimovies[25];
		System.out.println(h26);
		String h27=hindimovies[26];
		System.out.println(h27);
		String h28=hindimovies[27];
		System.out.println(h28);
		String h29=hindimovies[28];
		System.out.println(h29);
		String h30=hindimovies[29];
		System.out.println(h30);
		System.out.println("Tamil Movies are:");
		String t1=tamilmovies[0];
		System.out.println(t1);
		String t2=tamilmovies[1];
		System.out.println(t2);
		String t3=tamilmovies[2];
		System.out.println(t3);
		String t4=tamilmovies[3];
		System.out.println(t4);
		String t5=tamilmovies[4];
		System.out.println(t5);
		String t6=tamilmovies[5];
		System.out.println(t6);
		String t7=tamilmovies[6];
		System.out.println(t7);
		String t8=tamilmovies[7];
		System.out.println(t8);
		String t9=tamilmovies[8];
		System.out.println(t9);
		String t10=tamilmovies[9];
		System.out.println(t10);
		String t11=tamilmovies[10];
		System.out.println(t11);
		String t12=tamilmovies[11];
		System.out.println(t12);
		String t13=tamilmovies[12];
		System.out.println(t13);
		String t14=tamilmovies[13];
		System.out.println(t14);
		String t15=tamilmovies[14];
		System.out.println(t15);
		String t16=tamilmovies[15];
		System.out.println(t16);
		String t17=tamilmovies[16];
		System.out.println(t17);
		String t18=tamilmovies[17];
		System.out.println(t18);
		String t19=tamilmovies[18];
		System.out.println(t19);
		String t20=tamilmovies[19];
		System.out.println(t20);
		String t21=tamilmovies[20];
		System.out.println(t21);
		String t22=tamilmovies[21];
		System.out.println(t22);
		String t23=tamilmovies[22];
		System.out.println(t23);
		String t24=tamilmovies[23];
		System.out.println(t24);
		String t25=tamilmovies[24];
		System.out.println(t25);
		String t26=tamilmovies[25];
		System.out.println(t26);
		String t27=tamilmovies[26];
		System.out.println(t27);
		String t28=tamilmovies[27];
		System.out.println(t28);
		String t29=tamilmovies[28];
		System.out.println(t29);
		String t30=tamilmovies[29];
		System.out.println(t30);
		System.out.println("Telghu Movies are:");
		String te1=telgumovies[0];
		System.out.println(te1);
		String te2=telgumovies[1];
		System.out.println(te2);
		String te3=telgumovies[2];
		System.out.println(te3);
		String te4=telgumovies[3];
		System.out.println(te4);
		String te5=telgumovies[4];
		System.out.println(te5);
		String te6=telgumovies[5];
		System.out.println(te6);
		String te7=telgumovies[6];
		System.out.println(te7);
		String te8=telgumovies[7];
		System.out.println(te8);
		String te9=telgumovies[8];
		System.out.println(te9);
		String te10=telgumovies[9];
		System.out.println(te10);
		String te11=telgumovies[10];
		System.out.println(te11);
		String te12=telgumovies[11];
		System.out.println(te12);
		String te13=telgumovies[12];
		System.out.println(te13);
		String te14=telgumovies[13];
		System.out.println(te14);
		String te15=telgumovies[14];
		System.out.println(te15);
		String te16=telgumovies[15];
		System.out.println(te16);
		String te17=telgumovies[16];
		System.out.println(te17);
		String te18=telgumovies[17];
		System.out.println(te18);
		String te19=telgumovies[18];
		System.out.println(te19);
		String te20=telgumovies[19];
		System.out.println(te20);
		String te21=telgumovies[20];
		System.out.println(te21);
		String te22=telgumovies[21];
		System.out.println(te22);
		String te23=telgumovies[22];
		System.out.println(te23);
		String te24=telgumovies[23];
		System.out.println(te24);
		String te25=telgumovies[24];
		System.out.println(te25);
		String te26=telgumovies[25];
		System.out.println(te26);
		String te27=telgumovies[26];
		System.out.println(te27);
		String te28=telgumovies[27];
		System.out.println(te28);
		String te29=telgumovies[28];
		System.out.println(te29);
		String te30=telgumovies[29];
		System.out.println(te30);
		System.out.println("Malyalam  Movies are:");
		String m1=malyalammovies[0];
		System.out.println(m1);
		String m2=malyalammovies[1];
		System.out.println(m2);
		String m3=malyalammovies[2];
		System.out.println(m3);
		String m4=malyalammovies[3];
		System.out.println(m4);
		String m5=malyalammovies[4];
		System.out.println(m5);
		String m6=malyalammovies[5];
		System.out.println(m6);
		String m7=malyalammovies[6];
		System.out.println(m7);
		String m8=malyalammovies[7];
		System.out.println(m8);
		String m9=malyalammovies[8];
		System.out.println(m9);
		String m10=malyalammovies[9];
		System.out.println(m10);
		String m11=malyalammovies[10];
		System.out.println(m11);
		String m12=malyalammovies[11];
		System.out.println(m12);
		String m13=malyalammovies[12];
		System.out.println(m13);
		String m14=malyalammovies[13];
		System.out.println(m14);
		String m15=malyalammovies[14];
		System.out.println(m15);
		String m16=malyalammovies[15];
		System.out.println(m16);
		String m17=malyalammovies[16];
		System.out.println(m17);
		String m18=malyalammovies[17];
		System.out.println(m18);
		String m19=malyalammovies[18];
		System.out.println(m19);
		String m20=malyalammovies[19];
		System.out.println(m20);
		String m21=malyalammovies[20];
		System.out.println(m21);
		String m22=malyalammovies[21];
		System.out.println(m22);
		String m23=malyalammovies[22];
		System.out.println(m23);
		String m24=malyalammovies[23];
		System.out.println(m24);
		String m25=malyalammovies[24];
		System.out.println(m25);
		String m26=malyalammovies[25];
		System.out.println(m26);
		String m27=malyalammovies[26];
		System.out.println(m27);
		String m28=malyalammovies[27];
		System.out.println(m28);
		String m29=malyalammovies[28];
		System.out.println(m29);
		String m30=malyalammovies[29];
		System.out.println(m30);
		System.out.println("English Movies are:");
		String e1=englishmovies[0];
		System.out.println(e1);
		String e2=englishmovies[1];
		System.out.println(e2);
		String e3=englishmovies[2];
		System.out.println(e3);
		String e4=englishmovies[3];
		System.out.println(e4);
		String e5=englishmovies[4];
		System.out.println(e5);
		String e6=englishmovies[5];
		System.out.println(e6);
		String e7=englishmovies[6];
		System.out.println(e7);
		String e8=englishmovies[7];
		System.out.println(e8);
		String e9=englishmovies[8];
		System.out.println(e9);
		String e10=englishmovies[9];
		System.out.println(e10);
		String e11=englishmovies[10];
		System.out.println(e11);
		String e12=englishmovies[11];
		System.out.println(e12);
		String e13=englishmovies[12];
		System.out.println(e13);
		String e14=englishmovies[13];
		System.out.println(e14);
		String e15=englishmovies[14];
		System.out.println(e15);
		String e16=englishmovies[15];
		System.out.println(e16);
		String e17=englishmovies[16];
		System.out.println(e17);
		String e18=englishmovies[17];
		System.out.println(e18);
		String e19=englishmovies[18];
		System.out.println(e19);
		String e20=englishmovies[19];
		System.out.println(e20);
		String e21=englishmovies[20];
		System.out.println(e21);
		String e22=englishmovies[21];
		System.out.println(e22);
		String e23=englishmovies[22];
		System.out.println(e23);
		String e24=englishmovies[23];
		System.out.println(e24);
		String e25=englishmovies[24];
		System.out.println(e25);
		String e26=englishmovies[25];
		System.out.println(e26);
		String e27=englishmovies[26];
		System.out.println(e27);
		String e28=englishmovies[27];
		System.out.println(e28);
		String e29=englishmovies[28];
		System.out.println(e29);
		String e30=englishmovies[29];
		System.out.println(e30);
		
		
		
		
		
	}
}	
		