class Heater
{
	static String brand="Richard's";
	static 	String special_feature="Interior";
	static 	String colour="white";
	static 	String form_factor="new";
	static 	String indoororoutdoorusage="Outdoor";
	static 	String product_dimensions="‎10D x 5W x 10H Centimeters ";
	static 	String recommendedusesforproduct="out";
	static 	String mounting="mount";
	static 	String room="Guest room";
	static 	String voltage="120 Volts";
	static 	double manufacturer_year=2020;
	static 	String manufacturer="China";
	static 	String country_of_origin="China";
	static 	String item_model_number="Gravio";
	static 	String asin="‎20D x 15W x 20H Centimeters ";
	static 	String manufacturer_location="china";
	static 	String packer="China";
	static 	String item_weight="2 kg";
	static 	String net_quantity="2 Count";
	static 	String components= "1 rooms heater";
	static 	String generic_name="Gravio";
	static 	String best_sellers_rank="#12,890 in Guest rooms";
	public static void main(String[] args)
	{
		String brand="Havells";
		String special_feature="Cool Touch Exterior";
		String colour="Black";
		String form_factor="Pedestal";
		String indoororoutdoorusage="Indoor";
		String product_dimensions="‎20D x 15W x 20H Centimeters ";
		String recommendedusesforproduct="Home";
		String mounting="Tabletop Mount";
		String room=" ‎Bedroom";
		String voltage="230 Volts(AC)";
		double manufacturer_year=2024;
		String manufacturer="Havells, India ,Ltd";
		String country_of_origin="India";
		String item_model_number="‎Inclino‎";
		String asin="‎‎B0BPBZL1KB ";
		String manufacturer_location="Havells India Limited, Havells India Ltd";
		String packer="Havells India Ltd.";
		String item_weight="3 kg 200 g";
		String net_quantity=" 1 Count";
		String components=" 1N Room Heater, 1N User Manual";
		String generic_name="Rod Halogen Heater ";
		String best_sellers_rank="#24,153 in Home & Kitchen (See Top 100 in Home & Kitchen)#5 in Halogen Heaters";
		System.out.println(" Brand is : " + brand);
		System.out.println(" Brand is : " + Heater.brand);
		System.out.println(" Special Feature is : " + special_feature);
		System.out.println(" Special Feature is : " + Heater.special_feature);
		System.out.println(" Colour is : " + colour);
		System.out.println(" Colour is : " + Heater.colour);
		System.out.println("Form Factor is : " + form_factor);
		System.out.println("Form Factor is : " + Heater.form_factor);
		System.out.println(" Indoor or Outdoor Usage is : " + indoororoutdoorusage);
		System.out.println(" Indoor or Outdoor Usage is : " + Heater.indoororoutdoorusage);
		System.out.println(" Product Dimensions is : " + product_dimensions);
		System.out.println(" Product Dimensions is : " + Heater.product_dimensions);
		System.out.println(" Recommendations of product : " + recommendedusesforproduct);
		System.out.println(" Recommendations of product : " + Heater.recommendedusesforproduct);
		System.out.println(" Mounting type is : " + mounting);
		System.out.println(" Mounting type is : " + Heater.mounting);
		System.out.println(" Room type is : " + room);
		System.out.println(" Room type is : " + Heater.room);
		System.out.println(" Voltage is : " + voltage);
		System.out.println(" Voltage is : " + Heater.voltage);
		System.out.println(" Manufacturer Year is : " + manufacturer_year);
		System.out.println(" Manufacturer Year is : " + Heater.manufacturer_year);
		System.out.println(" Manufacturer  is : " + manufacturer);
		System.out.println(" Manufacturer  is : " + Heater.manufacturer);
		System.out.println(" Country Of Origin is : " + country_of_origin);
		System.out.println(" Country Of Origin is : " + Heater.country_of_origin);
		System.out.println(" Item Model Number is : " + item_model_number);
		System.out.println(" Item Model Number is : " + Heater.item_model_number);
		System.out.println(" ASIN is : " + asin);
		System.out.println(" ASIN is : " + Heater.asin);
		System.out.println(" Manufacturer is : " + manufacturer_location);
		System.out.println(" Manufacturer is : " + Heater.manufacturer_location);
		System.out.println(" PACKER is : " + packer);
		System.out.println(" PACKER is : " + Heater.packer);
		System.out.println(" Item Weight is : " + item_weight);
		System.out.println(" Item Weight is : " + Heater.item_weight);
		System.out.println(" Net Quantity is : " + net_quantity);
		System.out.println(" Net Quantity is : " + Heater.net_quantity);
		System.out.println(" Components are : " + components);
		System.out.println(" Components are : " + Heater.components);
		System.out.println(" Generic Name is : " + generic_name);
		System.out.println(" Generic Name is : " + Heater.generic_name);
		System.out.println(" Best sellers Rank is : " + best_sellers_rank);
		System.out.println(" Best sellers Rank is : " + Heater.best_sellers_rank);
	}
}