class SmartWatch
{
	static String brand="Sound";
	static	String manufacturer="Neba";
	static	String series="sound";
	static	String colour="Silver";
	static	String item_height="4.5 centimeters";
	static	String item_width="3.3 centimeters";
	static	String standing_screen_display_size="2.5 inches";
	static	String product_dimentions="8.1*10.4*10.5 cm;0.05g";
	static	String batteries="2 Lithium";
	static	String item_model_number="web-sw-txistgo-meshmtl-gld_gld";
	static	String connectivity="B1";
	static	String wireless="B1";
	static	String wattage="10 Watts";
	static	String operating_system="B1";
	static	String averagebatteylife="B1";
	static	String batteriesincluded="no";
	static	String lithium_battery="110 milliamphere";
	static	String lithium_battery_weight="no";
	static	int ion_cells=2;
	static	int metal_cells=2;
	static	String components="smart watch";
	static	String country_of_origin="China";
	static	String item_weight="1 kg";
	public static void main(String[] args)
	{
		String brand="Noise";
		String manufacturer="Nexxbase Marketing Pvt, Ltd, Noise";
		String series="NoiseFit";
		String colour="Gold Link";
		String item_height="10.5 Centimeters";
		String item_width="10.4 Centimeters";
		String standing_screen_display_size="1.3 inches";
		String product_dimentions="7.1*10.4*10.5 cm;0.05g";
		String batteries="1 Lithium lon batteries required(included)";
		String item_model_number="wrb-sw-twistgo-meshmtl-gld_gld";
		String connectivity="Bluetooth";
		String wireless="Bluetooth";
		String wattage="15 Watts";
		String operating_system="SmartWatch";
		String averagebatteylife="7 Days";
		String batteriesincluded="Yes";
		String lithium_battery="210 Milliampere Hour(mAh)";
		String lithium_battery_weight="35 Grams";
		int ion_cells=1;
		int metal_cells=1;
		String components="SmartWatch, Magnetic Charger, User Manual, Warranty Card";
		String country_of_origin="India";
		String item_weight="0.05g";
		System.out.println("The Brand is : " + brand);
		System.out.println("The Manufacturer is : " + manufacturer);
		System.out.println("The Series : " + series);
		System.out.println("The Colour : " + colour);
		System.out.println("The Item Height is : " + item_height);
		System.out.println("The Item Width is : " + item_width);
		System.out.println("The Standing Screen Size Display is: " + standing_screen_display_size);
		System.out.println("The Product Dimension is:" + product_dimentions);
		System.out.println("The Batteries is: " + batteries);
		System.out.println("The Item Model Number is: " + item_model_number);
		System.out.println("The Connectivity type is: " + connectivity);
		System.out.println("The Wireless type is: " + wireless);
		System.out.println("The Wattage is :" + wattage);
		System.out.println("The Operating System is:" + operating_system);
		System.out.println("The Average battery Life is :" + averagebatteylife);
		System.out.println("If batteries included  :" + batteriesincluded);
		System.out.println("The Lithium Battery  is: " + lithium_battery);
		System.out.println("The Liithium Battery Weight is: " + lithium_battery_weight);
		System.out.println("Number of Lithium Ion cells : " + ion_cells);
		System.out.println("Number of Lithium Metal Cells : " + metal_cells);
		System.out.println("The Components : " + components);
		System.out.println("The Country Of Origin : " + country_of_origin);
		System.out.println("The Item Weight : " + item_weight);
	}
}